dist: bionic
group: deprecated-2017Q2
sudo: required
language: java
install: mvn install -DskipTests=true -Dgpg.skip=true
jdk:
  - openjdk7
  - openjdk8
  - openjdk9
  - openjdk10
<<<<<<< Upstream, based on hexdouble
=======
  - openjdk11
>>>>>>> 41f0fb9 update supported JDK
services:
  - docker
before_script:
  - docker run -e TZ=Europe/Moscow -d -p 127.0.0.1:8123:8123 --name some-clickhouse-server --ulimit nofile=262144:262144 yandex/clickhouse-server:latest
